@startuml
left to right direction

actor "The user" as user
package backend{
    (service)
    (Database) as db
}
queue RabbitMQ as rabbit

service<--rabbit
service.>(db)
:user:..>(service)

note right of user: This is a user

note "a note" as mynote

user --> mynote
mynote -->rabbit


@enduml