@startuml
left to right direction

node node1
node node2
node node3
node node4
node node5
node node6
node node7
node node8
node node9
node node10
node1 --> node2
node1 --* node3
node1 --o node4
node1 --+ node5
node1 --# node6
node1 -->> node7
node1 --0 node8
node1 --^ node9
node1 --(0 node10

@enduml
