@startuml
' left to right direction

rectangle "DB Servers" #LightYellow {
    database "Auth Databases" as authdb #lightblue
    database "User Database" as userdb #lightblue
}

actor " " as actor

rectangle "kubernetes"{
    [Auth]
    queue RabbitMQ as authRabbit #orange
    queue RabbitMQ as monolithRabbit #orange
    (Kong-Gateway) as kong #application

    [User]
    [Email]

    usecase Monolith as "..<b>Monolith Services</b>..
    
    Exports
    Payment
    Ticket
    Plans
    Session logs-connections
    Order-PI
    File"
}

actor<->kong
kong<->Monolith
Monolith<-->monolithRabbit
authdb<-->Auth
userdb<-->User
User->authRabbit
authRabbit->Auth
User<-->Monolith
Email<-->Monolith

@enduml